name: Commit and Push a File

on:
  push:  # Запускается при каждом `git push`
  workflow_dispatch:  # Позволяет запускать вручную через вкладку Actions

jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git Remote
        run: |
          git remote remove origin || true
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Устанавливаем pytest

      - name: Run Pytest
        run: pytest >> log_pytest.txt  # Запуск тестов и сохранение в файл

      - name: Commit and Push Changes
        run: |
          ls -a
          git add .
          git commit -m "random file from action"
          git push

